### ISSUE TITLE
crawler貌似无法运行

### ISSUE THREAD

**Issue by awesomeric** [HOUCe/node-crawler-jianshu#1]
是不是有个大括号打多了。另外，我修改了你的crawler那个爬虫以后只能爬取数组第一个文章的信息。
希望能review代码一下

**Comment by HOUCe** [comment]
我看了一下，大括号并没有打多。是因为我把我的邮箱信息配置删掉了。如果想把代码跑起来，需要加入自己的邮箱账户名和密码。
我不想因为把自己的邮箱密码留在代码里呀。。。😄

另外“只能爬取数组第一个文章的信息”是因为我把我的一篇文章删除了，囧。。。
所以articleIds数组的第一项匹配不到。

建议根据代码结构，自己手动实现爬取一个网站，或者自己的简书内容。一定会有收获的！

**Comment by awesomeric** [comment]
谢谢，我发现了都是我自己的问题，所以及时关闭了issue。十分感谢你的分享，学到不少。话说promise对象不需要显式引入吧，es6原生不就是有这个方法咩?另外我在爬取一些博客信息的时候如果它们有翻页逻辑的时候如何来触发翻页的效果呢，请赐教

**Comment by HOUCe** [comment]
如果是静态网页的话可以匹配到“下一页”的标签，获取该URL，然后继续爬取。

Babel 默认只转换新的 JavaScript 句法（syntax），而不转换新的 API ，比如 Iterator、Generator、Set、Maps、Proxy、Reflect、Symbol、Promise 等全局对象，以及一些定义在全局对象上的方法（比如 Object.assign）都不会转码。

引入Promise Pollyfill主要是为了兼容性，其实确实没什么必要。
